// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/car/data/repo/car_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:kcars/features/app_settings/data/model/sort_model.dart' as _i18;
import 'package:kcars/features/car/data/model/brand.dart' as _i10;
import 'package:kcars/features/car/data/model/car.dart' as _i2;
import 'package:kcars/features/car/data/model/car_cursor.dart' as _i14;
import 'package:kcars/features/car/data/model/car_post.dart' as _i7;
import 'package:kcars/features/car/data/model/car_type.dart' as _i15;
import 'package:kcars/features/car/data/model/featured_cars.dart' as _i17;
import 'package:kcars/features/car/data/model/filter.dart' as _i11;
import 'package:kcars/features/car/data/model/filter_data.dart' as _i3;
import 'package:kcars/features/car/data/model/image.dart' as _i8;
import 'package:kcars/features/car/data/model/paginated.dart' as _i4;
import 'package:kcars/features/car/data/model/paln.dart' as _i16;
import 'package:kcars/features/car/data/model/post_location.dart' as _i9;
import 'package:kcars/features/car/data/model/promotion.dart' as _i12;
import 'package:kcars/features/car/data/remote/car_remote.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCar_0 extends _i1.SmartFake implements _i2.Car {
  _FakeCar_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFilterData_1 extends _i1.SmartFake implements _i3.FilterData {
  _FakeFilterData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginated_2 extends _i1.SmartFake implements _i4.Paginated {
  _FakePaginated_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CarRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRemote extends _i1.Mock implements _i5.CarRemote {
  MockCarRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> listCar(_i7.CarPost? car) =>
      (super.noSuchMethod(
            Invocation.method(#listCar, [car]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateCar(_i7.CarPost? car) =>
      (super.noSuchMethod(
            Invocation.method(#updateCar, [car]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sortImages(List<_i8.Images>? images) =>
      (super.noSuchMethod(
            Invocation.method(#sortImages, [images]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCar(String? carId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCar, [carId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.Car>> suggestedCars([_i9.PostLocation? param]) =>
      (super.noSuchMethod(
            Invocation.method(#suggestedCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i2.Car>> nearBayCars([_i9.PostLocation? param]) =>
      (super.noSuchMethod(
            Invocation.method(#nearBayCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i10.Brand>> brandCars([_i9.PostLocation? param]) =>
      (super.noSuchMethod(
            Invocation.method(#brandCars, [param]),
            returnValue: _i6.Future<List<_i10.Brand>>.value(<_i10.Brand>[]),
          )
          as _i6.Future<List<_i10.Brand>>);

  @override
  _i6.Future<List<_i2.Car>> recentlyViewed() =>
      (super.noSuchMethod(
            Invocation.method(#recentlyViewed, []),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i2.Car>> filterCars([_i11.Filter? param]) =>
      (super.noSuchMethod(
            Invocation.method(#filterCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<_i2.Car> detailCars(String? carId) =>
      (super.noSuchMethod(
            Invocation.method(#detailCars, [carId]),
            returnValue: _i6.Future<_i2.Car>.value(
              _FakeCar_0(this, Invocation.method(#detailCars, [carId])),
            ),
          )
          as _i6.Future<_i2.Car>);

  @override
  _i6.Future<String?> favoriteCar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#favoriteCar, [id]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<_i2.Car>> favoriteCars([String? cursor]) =>
      (super.noSuchMethod(
            Invocation.method(#favoriteCars, [cursor]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<String> promotion(_i12.Promotion? promotion) =>
      (super.noSuchMethod(
            Invocation.method(#promotion, [promotion]),
            returnValue: _i6.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#promotion, [promotion]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> updatePromotion(_i12.PromotionUpdate? promotion) =>
      (super.noSuchMethod(
            Invocation.method(#updatePromotion, [promotion]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletePromotion(String? promotionId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePromotion, [promotionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i12.Promotion>> promotions([_i12.PromotionPost? param]) =>
      (super.noSuchMethod(
            Invocation.method(#promotions, [param]),
            returnValue: _i6.Future<List<_i12.Promotion>>.value(
              <_i12.Promotion>[],
            ),
          )
          as _i6.Future<List<_i12.Promotion>>);

  @override
  _i6.Future<List<_i2.Car>> companyCars([_i14.CarsCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#companyCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i2.Car>> userCompanyCars(_i14.CarsCursor? param) =>
      (super.noSuchMethod(
            Invocation.method(#userCompanyCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i2.Car>> allCars(_i14.CarsCursor? param) =>
      (super.noSuchMethod(
            Invocation.method(#allCars, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<_i3.FilterData> filtersData() =>
      (super.noSuchMethod(
            Invocation.method(#filtersData, []),
            returnValue: _i6.Future<_i3.FilterData>.value(
              _FakeFilterData_1(this, Invocation.method(#filtersData, [])),
            ),
          )
          as _i6.Future<_i3.FilterData>);

  @override
  _i6.Future<List<_i15.CarType>> carTypes() =>
      (super.noSuchMethod(
            Invocation.method(#carTypes, []),
            returnValue: _i6.Future<List<_i15.CarType>>.value(<_i15.CarType>[]),
          )
          as _i6.Future<List<_i15.CarType>>);

  @override
  _i6.Future<List<_i10.Brand>> brands() =>
      (super.noSuchMethod(
            Invocation.method(#brands, []),
            returnValue: _i6.Future<List<_i10.Brand>>.value(<_i10.Brand>[]),
          )
          as _i6.Future<List<_i10.Brand>>);

  @override
  _i6.Future<List<_i16.Plan>> plans() =>
      (super.noSuchMethod(
            Invocation.method(#plans, []),
            returnValue: _i6.Future<List<_i16.Plan>>.value(<_i16.Plan>[]),
          )
          as _i6.Future<List<_i16.Plan>>);

  @override
  _i6.Future<_i4.Paginated> cars([String? cursor]) =>
      (super.noSuchMethod(
            Invocation.method(#cars, [cursor]),
            returnValue: _i6.Future<_i4.Paginated>.value(
              _FakePaginated_2(this, Invocation.method(#cars, [cursor])),
            ),
          )
          as _i6.Future<_i4.Paginated>);

  @override
  _i6.Future<List<_i2.Car>> explorerMap([_i9.PostLocation? param]) =>
      (super.noSuchMethod(
            Invocation.method(#explorerMap, [param]),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<List<_i2.Car>> featuredCars() =>
      (super.noSuchMethod(
            Invocation.method(#featuredCars, []),
            returnValue: _i6.Future<List<_i2.Car>>.value(<_i2.Car>[]),
          )
          as _i6.Future<List<_i2.Car>>);

  @override
  _i6.Future<String?> newFeaturedCar(_i17.FeaturedCars? param) =>
      (super.noSuchMethod(
            Invocation.method(#newFeaturedCar, [param]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> sortFeaturedCar(List<_i18.SortModel>? param) =>
      (super.noSuchMethod(
            Invocation.method(#sortFeaturedCar, [param]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteFeaturedCar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFeaturedCar, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
