// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/auth/data/repository/auth_repo_impl.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kcars/features/auth/data/model/auth.dart' as _i3;
import 'package:kcars/features/auth/data/model/profile.dart' as _i2;
import 'package:kcars/features/auth/data/remote/auth_remote.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuth_1 extends _i1.SmartFake implements _i3.Auth {
  _FakeAuth_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemote extends _i1.Mock implements _i4.AuthRemote {
  MockAuthRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Profile> login(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#login, [param]),
            returnValue: _i5.Future<_i2.Profile>.value(
              _FakeProfile_0(this, Invocation.method(#login, [param])),
            ),
          )
          as _i5.Future<_i2.Profile>);

  @override
  _i5.Future<_i2.Profile> signup(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [param]),
            returnValue: _i5.Future<_i2.Profile>.value(
              _FakeProfile_0(this, Invocation.method(#signup, [param])),
            ),
          )
          as _i5.Future<_i2.Profile>);

  @override
  _i5.Future<void> logout(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Profile> refreshProfile([bool? isCheking]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, [isCheking]),
            returnValue: _i5.Future<_i2.Profile>.value(
              _FakeProfile_0(
                this,
                Invocation.method(#refreshProfile, [isCheking]),
              ),
            ),
          )
          as _i5.Future<_i2.Profile>);

  @override
  _i5.Future<void> updateName(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateEmailSendOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailSendOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateEmailVerifyOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailVerifyOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetSendOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetSendOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetVerifyOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetVerifyOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Auth> updateProfilePicture(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [param]),
            returnValue: _i5.Future<_i3.Auth>.value(
              _FakeAuth_1(
                this,
                Invocation.method(#updateProfilePicture, [param]),
              ),
            ),
          )
          as _i5.Future<_i3.Auth>);

  @override
  _i5.Future<void> updatePreflang(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreflang, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePhoneNumber(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyEmailSendOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailSendOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> verifyEmailVerifyOtp(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailVerifyOtp, [param]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Auth> refreshToken(_i3.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [param]),
            returnValue: _i5.Future<_i3.Auth>.value(
              _FakeAuth_1(this, Invocation.method(#refreshToken, [param])),
            ),
          )
          as _i5.Future<_i3.Auth>);
}
