// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/auth/presentation/riverpod/auth_controller.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:device_info_plus/device_info_plus.dart' as _i2;
import 'package:fpdart/src/either.dart' as _i5;
import 'package:kcars/configs/error/failure.dart' as _i6;
import 'package:kcars/core/services/device_info_service.dart' as _i11;
import 'package:kcars/core/services/secure_storage.dart' as _i10;
import 'package:kcars/features/auth/data/model/auth.dart' as _i8;
import 'package:kcars/features/auth/data/model/profile.dart' as _i7;
import 'package:kcars/features/auth/data/model/session.dart' as _i12;
import 'package:kcars/features/auth/domain/repository/auth_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceInfoPlugin_0 extends _i1.SmartFake
    implements _i2.DeviceInfoPlugin {
  _FakeDeviceInfoPlugin_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i3.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>> login(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#login, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Profile>>(
                this,
                Invocation.method(#login, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>> signup(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Profile>>(
                this,
                Invocation.method(#signup, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> logout(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#logout, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>> refreshProfile([
    bool? isCheking,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#refreshProfile, [isCheking]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, _i7.Profile>>(
                this,
                Invocation.method(#refreshProfile, [isCheking]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Profile>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updateName(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updateName, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updatePassword(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updatePassword, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updateEmailSendOtp(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailSendOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updateEmailSendOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updateEmailVerifyOtp(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailVerifyOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updateEmailVerifyOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resetSendOtp(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetSendOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#resetSendOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resetVerifyOtp(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetVerifyOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#resetVerifyOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> resetPassword(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#resetPassword, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updatePreflang(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreflang, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updatePreflang, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>> updateProfilePicture(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, _i8.Auth>>(
                this,
                Invocation.method(#updateProfilePicture, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updatePhoneNumber(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updatePhoneNumber, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> verifyEmailSendOtp(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailSendOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#verifyEmailSendOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> verifyEmailVerifyOtp(
    _i8.Auth? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailVerifyOtp, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#verifyEmailVerifyOtp, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>> refreshToken(_i8.Auth? param) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [param]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, _i8.Auth>>(
                this,
                Invocation.method(#refreshToken, [param]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i8.Auth>>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i10.SecureStorage {
  MockSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> setData(_i7.Profile? userData) =>
      (super.noSuchMethod(
            Invocation.method(#setData, [userData]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<dynamic> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<bool> setSession({
    required String? accessToken,
    required String? refreshToekn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [], {
              #accessToken: accessToken,
              #refreshToekn: refreshToekn,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getAcessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAcessToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> setTokenExpiry(String? expireTime) =>
      (super.noSuchMethod(
            Invocation.method(#setTokenExpiry, [expireTime]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getTokenExpiry() =>
      (super.noSuchMethod(
            Invocation.method(#getTokenExpiry, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> write(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> read(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#read, [key]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeviceInfoSerice].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoSerice extends _i1.Mock implements _i11.DeviceInfoSerice {
  MockDeviceInfoSerice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceInfoPlugin get deviceInfo =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfo),
            returnValue: _FakeDeviceInfoPlugin_0(
              this,
              Invocation.getter(#deviceInfo),
            ),
          )
          as _i2.DeviceInfoPlugin);

  @override
  _i4.Future<_i2.BaseDeviceInfo?> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.BaseDeviceInfo?>.value(),
          )
          as _i4.Future<_i2.BaseDeviceInfo?>);

  @override
  _i4.Future<_i2.AndroidDeviceInfo?> androidInfo() =>
      (super.noSuchMethod(
            Invocation.method(#androidInfo, []),
            returnValue: _i4.Future<_i2.AndroidDeviceInfo?>.value(),
          )
          as _i4.Future<_i2.AndroidDeviceInfo?>);

  @override
  _i4.Future<_i2.IosDeviceInfo?> iosInfo() =>
      (super.noSuchMethod(
            Invocation.method(#iosInfo, []),
            returnValue: _i4.Future<_i2.IosDeviceInfo?>.value(),
          )
          as _i4.Future<_i2.IosDeviceInfo?>);

  @override
  _i4.Future<_i12.Session?> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i4.Future<_i12.Session?>.value(),
          )
          as _i4.Future<_i12.Session?>);
}
