// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/company/company_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/src/either.dart' as _i4;
import 'package:kcars/configs/error/failure.dart' as _i5;
import 'package:kcars/features/car/data/model/city.dart' as _i11;
import 'package:kcars/features/company/data/model/company.dart' as _i9;
import 'package:kcars/features/company/data/model/company_cursor.dart' as _i10;
import 'package:kcars/features/company/data/model/company_statistic.dart'
    as _i12;
import 'package:kcars/features/company/data/model/contact.dart' as _i8;
import 'package:kcars/features/company/data/model/post_company.dart' as _i6;
import 'package:kcars/features/company/domain/company_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CompanyRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyRepo extends _i1.Mock implements _i2.CompanyRepo {
  MockCompanyRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateCompany(
    _i6.PostCompany? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCompany, [params]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateCompany, [params]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> sortContacts(
    List<_i8.Contact>? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sortContacts, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#sortContacts, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>> companies([
    _i10.CompanyCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companies, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Company>>>(
                    this,
                    Invocation.method(#companies, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> newCompany(_i9.Company? param) =>
      (super.noSuchMethod(
            Invocation.method(#newCompany, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#newCompany, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.Company>> company(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#company, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i9.Company>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i9.Company>>(
                this,
                Invocation.method(#company, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i9.Company>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.Company>> myCompany([String? id]) =>
      (super.noSuchMethod(
            Invocation.method(#myCompany, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i9.Company>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i9.Company>>(
                this,
                Invocation.method(#myCompany, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i9.Company>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.City>>> cities() =>
      (super.noSuchMethod(
            Invocation.method(#cities, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i11.City>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i11.City>>>(
                    this,
                    Invocation.method(#cities, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.City>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i12.CompanyStatistic>>>
  companyStatistic([DateTime? date]) =>
      (super.noSuchMethod(
            Invocation.method(#companyStatistic, [date]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i12.CompanyStatistic>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i12.CompanyStatistic>>
                  >(this, Invocation.method(#companyStatistic, [date])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i12.CompanyStatistic>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>> allCompanies([
    _i10.CompanyCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#allCompanies, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Company>>>(
                    this,
                    Invocation.method(#allCompanies, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Company>>>);
}
