// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/user/application/user_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/src/either.dart' as _i4;
import 'package:kcars/configs/error/failure.dart' as _i5;
import 'package:kcars/features/auth/data/model/permission.dart' as _i11;
import 'package:kcars/features/auth/data/model/profile.dart' as _i6;
import 'package:kcars/features/user/data/model/account_status.dart' as _i9;
import 'package:kcars/features/user/data/model/post_role.dart' as _i10;
import 'package:kcars/features/user/data/model/user_cursor.dart' as _i7;
import 'package:kcars/features/user/data/model/user_password.dart' as _i12;
import 'package:kcars/features/user/domain/repo/user_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepo extends _i1.Mock implements _i2.UserRepo {
  MockUserRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>> users([
    _i7.UserCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#users, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.Profile>>>(
                    this,
                    Invocation.method(#users, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>> bannedUsers([
    _i7.UserCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#bannedUsers, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.Profile>>>(
                    this,
                    Invocation.method(#bannedUsers, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Profile>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.AccountStatus>>> accountStatuses(
    _i7.UserCursor? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#accountStatuses, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i9.AccountStatus>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, List<_i9.AccountStatus>>
                  >(this, Invocation.method(#accountStatuses, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.AccountStatus>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> updateAccountStatus(
    _i9.AccountStatus? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccountStatus, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#updateAccountStatus, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateRole(_i10.PostRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [role]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateRole, [role]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteBan(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBan, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteBan, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.Permission>>> permissions() =>
      (super.noSuchMethod(
            Invocation.method(#permissions, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.Permission>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.Permission>>
                  >(this, Invocation.method(#permissions, [])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.Permission>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateUserPassword(
    _i12.UserPassword? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPassword, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateUserPassword, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> recoverAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#recoverAccount, [userId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i8.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#recoverAccount, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
