import 'package:kcars/core/services/type_defs.dart';
import 'package:kcars/features/app_settings/data/model/sort_model.dart';
import 'package:kcars/features/car/data/model/brand.dart';
import 'package:kcars/features/car/data/model/car.dart';
import 'package:kcars/features/car/data/model/car_cursor.dart';
import 'package:kcars/features/car/data/model/car_post.dart';
import 'package:kcars/features/car/data/model/car_type.dart';
import 'package:kcars/features/car/data/model/featured_cars.dart';
import 'package:kcars/features/car/data/model/filter.dart';
import 'package:kcars/features/car/data/model/filter_data.dart';
import 'package:kcars/features/car/data/model/image.dart';
import 'package:kcars/features/car/data/model/paginated.dart';
import 'package:kcars/features/car/data/model/paln.dart';
import 'package:kcars/features/car/data/model/post_location.dart';
import 'package:kcars/features/car/data/model/promotion.dart';

abstract class CarRepo {
  Result<void> listCar(CarPost car);
  Result<void> updateCar(CarPost car);
  Result<void> sortImages(List<Images> images);
  Result<void> deleteCar(String carId);
  Result<List<Car>> suggestedCars([PostLocation? param]);
  Result<List<Car>> nearBayCars([PostLocation? param]);
  Result<List<Brand>> brandCars([PostLocation? param]);
  Result<List<Car>> recentlyViewed();
  Result<List<Car>> filterCars([Filter? param]);
  Result<Car> detailCars(String carId);
  Result<String?> favoriteCar(String id);
  Result<List<Car>> favoriteCars([String? cursor]);
  Result<List<Promotion>> promotions([PromotionPost? param]);
  Result<String> promotion(Promotion promotion);
  Result<void> updatePromotion(PromotionUpdate promotion);
  Result<void> deletePromotion(String promotionId);
  Result<List<Car>> companyCars([CarsCursor? param]);
  Result<List<Car>> userCompanyCars(CarsCursor param);
  Result<List<Car>> allCars(CarsCursor param);
  Result<FilterData> filtersData();
  Result<List<CarType>> carTypes();
  Result<List<Brand>> brands();
  Result<List<Plan>> plans();
  Result<Paginated> cars([String? cursor]);
  Result<List<Car>> explorerMap([PostLocation? param]);
  Result<List<Car>> featuredCars();
  Result<String?> newFeaturedCar(FeaturedCars param);
  Result<void> sortFeaturedCar(List<SortModel> param);
  Result<void> deleteFeaturedCar(String id);
}
