// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/review/presentation/review_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/src/either.dart' as _i4;
import 'package:kcars/configs/error/failure.dart' as _i5;
import 'package:kcars/features/review/data/model/car_review.dart' as _i9;
import 'package:kcars/features/review/data/model/car_review_flag.dart' as _i12;
import 'package:kcars/features/review/data/model/company_review.dart' as _i11;
import 'package:kcars/features/review/data/model/company_review_flag.dart'
    as _i13;
import 'package:kcars/features/review/data/model/cursor_review.dart' as _i10;
import 'package:kcars/features/review/data/model/review_flag.dart' as _i8;
import 'package:kcars/features/review/data/model/review_post.dart' as _i6;
import 'package:kcars/features/review/data/model/updare_review.dart' as _i14;
import 'package:kcars/features/review/domain/repo/review_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReviewRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepo extends _i1.Mock implements _i2.ReviewRepo {
  MockReviewRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> reviewCar(
    _i6.ReviewPost? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reviewCar, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#reviewCar, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> reviewCompany(
    _i6.ReviewPost? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reviewCompany, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#reviewCompany, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> flagCarReview(
    _i8.ReviewFlag? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#flagCarReview, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#flagCarReview, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> flagCompanyReview(
    _i8.ReviewFlag? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#flagCompanyReview, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#flagCompanyReview, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>> carReviews(
    _i10.CursorReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#carReviews, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.CarReview>>>(
                    this,
                    Invocation.method(#carReviews, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>> companyReviews(
    _i10.CursorReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#companyReviews, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                  >(this, Invocation.method(#companyReviews, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>> companyCarsReviews([
    _i10.CursorReview? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companyCarsReviews, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.CarReview>>>(
                    this,
                    Invocation.method(#companyCarsReviews, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>>
  companiesReviews([_i10.CursorReview? param]) =>
      (super.noSuchMethod(
            Invocation.method(#companiesReviews, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                  >(this, Invocation.method(#companiesReviews, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>> allCarReviews(
    _i10.AllCursorReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allCarReviews, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.CarReview>>>(
                    this,
                    Invocation.method(#allCarReviews, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.CarReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>>
  allCompanyReviews(_i10.AllCursorReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#allCompanyReviews, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.CompanyReview>>
                  >(this, Invocation.method(#allCompanyReviews, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.CompanyReview>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i12.CarReviewFlag>>> carReviewFlags([
    _i10.CursorReviewFlags? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#carReviewFlags, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i12.CarReviewFlag>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i12.CarReviewFlag>>
                  >(this, Invocation.method(#carReviewFlags, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i12.CarReviewFlag>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i13.CompanyReviewFlag>>>
  companyReviewFlags([_i10.CursorReviewFlags? param]) =>
      (super.noSuchMethod(
            Invocation.method(#companyReviewFlags, [param]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i13.CompanyReviewFlag>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i13.CompanyReviewFlag>>
                  >(this, Invocation.method(#companyReviewFlags, [param])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i13.CompanyReviewFlag>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateCarReview(
    _i14.UpdateReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCarReview, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateCarReview, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateCompanyReview(
    _i14.UpdateReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCompanyReview, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateCompanyReview, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteCarReview(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCarReview, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteCarReview, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteCompanyReview(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCompanyReview, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteCompanyReview, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
