// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/booking/presentation/book_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/src/either.dart' as _i4;
import 'package:kcars/configs/error/failure.dart' as _i5;
import 'package:kcars/features/booking/data/model/book.dart' as _i10;
import 'package:kcars/features/booking/data/model/book_cursor.dart' as _i11;
import 'package:kcars/features/booking/data/model/new_booking.dart' as _i6;
import 'package:kcars/features/booking/data/model/promo_code.dart' as _i9;
import 'package:kcars/features/booking/data/model/promotion_result.dart' as _i8;
import 'package:kcars/features/booking/domain/repo/book_repo.dart' as _i2;
import 'package:kcars/features/company/data/model/contact_statistic.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepo extends _i1.Mock implements _i2.BookRepo {
  MockBookRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> bookCar([
    _i6.NewBooking? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#bookCar, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#bookCar, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i8.PromotionResult>> applyPromoCode(
    _i9.PromoCode? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyPromoCode, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i8.PromotionResult>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i8.PromotionResult>>(
                    this,
                    Invocation.method(#applyPromoCode, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i8.PromotionResult>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> cancelUserBooks([
    _i6.NewBooking? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUserBooks, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#cancelUserBooks, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>> getBooks([
    _i11.BookCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i10.Book>>>(
                    this,
                    Invocation.method(#getBooks, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>> allBooks([
    _i11.BookCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#allBooks, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i10.Book>>>(
                    this,
                    Invocation.method(#allBooks, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>> getCompanyBooks([
    _i11.BookCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyBooks, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i10.Book>>>(
                    this,
                    Invocation.method(#getCompanyBooks, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i10.Book>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateBook([
    _i6.NewBooking? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateBook, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> contact(
    _i12.ContactStatistic? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#contact, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#contact, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);
}
