// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/user/data/repo/user_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kcars/features/auth/data/model/permission.dart' as _i8;
import 'package:kcars/features/auth/data/model/profile.dart' as _i4;
import 'package:kcars/features/user/data/model/account_status.dart' as _i6;
import 'package:kcars/features/user/data/model/post_role.dart' as _i7;
import 'package:kcars/features/user/data/model/user_cursor.dart' as _i5;
import 'package:kcars/features/user/data/model/user_password.dart' as _i9;
import 'package:kcars/features/user/data/remote/user_remote.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemote extends _i1.Mock implements _i2.UserRemote {
  MockUserRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Profile>> users([_i5.UserCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#users, [param]),
            returnValue: _i3.Future<List<_i4.Profile>>.value(<_i4.Profile>[]),
          )
          as _i3.Future<List<_i4.Profile>>);

  @override
  _i3.Future<List<_i4.Profile>> bannedUsers([_i5.UserCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#bannedUsers, [param]),
            returnValue: _i3.Future<List<_i4.Profile>>.value(<_i4.Profile>[]),
          )
          as _i3.Future<List<_i4.Profile>>);

  @override
  _i3.Future<List<_i6.AccountStatus>> accountStatuses(_i5.UserCursor? param) =>
      (super.noSuchMethod(
            Invocation.method(#accountStatuses, [param]),
            returnValue: _i3.Future<List<_i6.AccountStatus>>.value(
              <_i6.AccountStatus>[],
            ),
          )
          as _i3.Future<List<_i6.AccountStatus>>);

  @override
  _i3.Future<String?> updateAccountStatus(_i6.AccountStatus? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccountStatus, [param]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> updateRole(_i7.PostRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [role]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBan(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBan, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.Permission>> permissions() =>
      (super.noSuchMethod(
            Invocation.method(#permissions, []),
            returnValue: _i3.Future<List<_i8.Permission>>.value(
              <_i8.Permission>[],
            ),
          )
          as _i3.Future<List<_i8.Permission>>);

  @override
  _i3.Future<void> updateUserPassword(_i9.UserPassword? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserPassword, [param]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> recoverAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#recoverAccount, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
