// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/car/application/car_controller.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/src/either.dart' as _i4;
import 'package:kcars/configs/error/failure.dart' as _i5;
import 'package:kcars/features/app_settings/data/model/sort_model.dart' as _i20;
import 'package:kcars/features/car/data/model/brand.dart' as _i11;
import 'package:kcars/features/car/data/model/car.dart' as _i9;
import 'package:kcars/features/car/data/model/car_cursor.dart' as _i14;
import 'package:kcars/features/car/data/model/car_post.dart' as _i6;
import 'package:kcars/features/car/data/model/car_type.dart' as _i16;
import 'package:kcars/features/car/data/model/featured_cars.dart' as _i19;
import 'package:kcars/features/car/data/model/filter.dart' as _i12;
import 'package:kcars/features/car/data/model/filter_data.dart' as _i15;
import 'package:kcars/features/car/data/model/image.dart' as _i8;
import 'package:kcars/features/car/data/model/paginated.dart' as _i18;
import 'package:kcars/features/car/data/model/paln.dart' as _i17;
import 'package:kcars/features/car/data/model/post_location.dart' as _i10;
import 'package:kcars/features/car/data/model/promotion.dart' as _i13;
import 'package:kcars/features/car/domain/repo/car_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CarRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCarRepo extends _i1.Mock implements _i2.CarRepo {
  MockCarRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> listCar(_i6.CarPost? car) =>
      (super.noSuchMethod(
            Invocation.method(#listCar, [car]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#listCar, [car]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateCar(_i6.CarPost? car) =>
      (super.noSuchMethod(
            Invocation.method(#updateCar, [car]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateCar, [car]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> sortImages(
    List<_i8.Images>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sortImages, [images]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#sortImages, [images]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteCar(String? carId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCar, [carId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteCar, [carId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> suggestedCars([
    _i10.PostLocation? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#suggestedCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#suggestedCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> nearBayCars([
    _i10.PostLocation? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#nearBayCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#nearBayCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>> brandCars([
    _i10.PostLocation? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#brandCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i11.Brand>>>(
                    this,
                    Invocation.method(#brandCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> recentlyViewed() =>
      (super.noSuchMethod(
            Invocation.method(#recentlyViewed, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#recentlyViewed, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> filterCars([
    _i12.Filter? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#filterCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#filterCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.Car>> detailCars(String? carId) =>
      (super.noSuchMethod(
            Invocation.method(#detailCars, [carId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i9.Car>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i9.Car>>(
                this,
                Invocation.method(#detailCars, [carId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i9.Car>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> favoriteCar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#favoriteCar, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#favoriteCar, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> favoriteCars([
    String? cursor,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#favoriteCars, [cursor]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#favoriteCars, [cursor]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i13.Promotion>>> promotions([
    _i13.PromotionPost? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#promotions, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i13.Promotion>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i13.Promotion>>>(
                    this,
                    Invocation.method(#promotions, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i13.Promotion>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String>> promotion(
    _i13.Promotion? promotion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#promotion, [promotion]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String>>(
                this,
                Invocation.method(#promotion, [promotion]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updatePromotion(
    _i13.PromotionUpdate? promotion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePromotion, [promotion]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updatePromotion, [promotion]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deletePromotion(
    String? promotionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePromotion, [promotionId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deletePromotion, [promotionId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> companyCars([
    _i14.CarsCursor? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companyCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#companyCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> userCompanyCars(
    _i14.CarsCursor? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#userCompanyCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#userCompanyCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> allCars(
    _i14.CarsCursor? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allCars, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#allCars, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i15.FilterData>> filtersData() =>
      (super.noSuchMethod(
            Invocation.method(#filtersData, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i15.FilterData>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i15.FilterData>>(
                    this,
                    Invocation.method(#filtersData, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i15.FilterData>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i16.CarType>>> carTypes() =>
      (super.noSuchMethod(
            Invocation.method(#carTypes, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i16.CarType>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i16.CarType>>>(
                    this,
                    Invocation.method(#carTypes, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i16.CarType>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>> brands() =>
      (super.noSuchMethod(
            Invocation.method(#brands, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i11.Brand>>>(
                    this,
                    Invocation.method(#brands, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.Brand>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i17.Plan>>> plans() =>
      (super.noSuchMethod(
            Invocation.method(#plans, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i17.Plan>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i17.Plan>>>(
                    this,
                    Invocation.method(#plans, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i17.Plan>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i18.Paginated>> cars([String? cursor]) =>
      (super.noSuchMethod(
            Invocation.method(#cars, [cursor]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i18.Paginated>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i18.Paginated>>(
                    this,
                    Invocation.method(#cars, [cursor]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i18.Paginated>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> explorerMap([
    _i10.PostLocation? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#explorerMap, [param]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#explorerMap, [param]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>> featuredCars() =>
      (super.noSuchMethod(
            Invocation.method(#featuredCars, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i9.Car>>>(
                    this,
                    Invocation.method(#featuredCars, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.Car>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, String?>> newFeaturedCar(
    _i19.FeaturedCars? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#newFeaturedCar, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, String?>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, String?>>(
                this,
                Invocation.method(#newFeaturedCar, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, String?>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> sortFeaturedCar(
    List<_i20.SortModel>? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sortFeaturedCar, [param]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#sortFeaturedCar, [param]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteFeaturedCar(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFeaturedCar, [id]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteFeaturedCar, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
