// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/review/data/repo/review_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:kcars/features/review/data/model/car_review.dart' as _i6;
import 'package:kcars/features/review/data/model/car_review_flag.dart' as _i9;
import 'package:kcars/features/review/data/model/company_review.dart' as _i8;
import 'package:kcars/features/review/data/model/company_review_flag.dart'
    as _i10;
import 'package:kcars/features/review/data/model/cursor_review.dart' as _i7;
import 'package:kcars/features/review/data/model/review_flag.dart' as _i5;
import 'package:kcars/features/review/data/model/review_post.dart' as _i4;
import 'package:kcars/features/review/data/model/updare_review.dart' as _i11;
import 'package:kcars/features/review/data/remote/review_remote.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReviewRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRemote extends _i1.Mock implements _i2.ReviewRemote {
  MockReviewRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> reviewCar(_i4.ReviewPost? param) =>
      (super.noSuchMethod(
            Invocation.method(#reviewCar, [param]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> reviewCompany(_i4.ReviewPost? param) =>
      (super.noSuchMethod(
            Invocation.method(#reviewCompany, [param]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> flagCarReview(_i5.ReviewFlag? param) =>
      (super.noSuchMethod(
            Invocation.method(#flagCarReview, [param]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> flagCompanyReview(_i5.ReviewFlag? param) =>
      (super.noSuchMethod(
            Invocation.method(#flagCompanyReview, [param]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<List<_i6.CarReview>> carReviews(_i7.CursorReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#carReviews, [param]),
            returnValue: _i3.Future<List<_i6.CarReview>>.value(
              <_i6.CarReview>[],
            ),
          )
          as _i3.Future<List<_i6.CarReview>>);

  @override
  _i3.Future<List<_i8.CompanyReview>> companyReviews(_i7.CursorReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#companyReviews, [param]),
            returnValue: _i3.Future<List<_i8.CompanyReview>>.value(
              <_i8.CompanyReview>[],
            ),
          )
          as _i3.Future<List<_i8.CompanyReview>>);

  @override
  _i3.Future<List<_i6.CarReview>> companyCarsReviews([
    _i7.CursorReview? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companyCarsReviews, [param]),
            returnValue: _i3.Future<List<_i6.CarReview>>.value(
              <_i6.CarReview>[],
            ),
          )
          as _i3.Future<List<_i6.CarReview>>);

  @override
  _i3.Future<List<_i8.CompanyReview>> companiesReviews([
    _i7.CursorReview? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companiesReviews, [param]),
            returnValue: _i3.Future<List<_i8.CompanyReview>>.value(
              <_i8.CompanyReview>[],
            ),
          )
          as _i3.Future<List<_i8.CompanyReview>>);

  @override
  _i3.Future<List<_i6.CarReview>> allCarReviews(_i7.AllCursorReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#allCarReviews, [param]),
            returnValue: _i3.Future<List<_i6.CarReview>>.value(
              <_i6.CarReview>[],
            ),
          )
          as _i3.Future<List<_i6.CarReview>>);

  @override
  _i3.Future<List<_i8.CompanyReview>> allCompanyReviews(
    _i7.AllCursorReview? param,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allCompanyReviews, [param]),
            returnValue: _i3.Future<List<_i8.CompanyReview>>.value(
              <_i8.CompanyReview>[],
            ),
          )
          as _i3.Future<List<_i8.CompanyReview>>);

  @override
  _i3.Future<List<_i9.CarReviewFlag>> carReviewFlags([
    _i7.CursorReviewFlags? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#carReviewFlags, [param]),
            returnValue: _i3.Future<List<_i9.CarReviewFlag>>.value(
              <_i9.CarReviewFlag>[],
            ),
          )
          as _i3.Future<List<_i9.CarReviewFlag>>);

  @override
  _i3.Future<List<_i10.CompanyReviewFlag>> companyReviewFlags([
    _i7.CursorReviewFlags? param,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#companyReviewFlags, [param]),
            returnValue: _i3.Future<List<_i10.CompanyReviewFlag>>.value(
              <_i10.CompanyReviewFlag>[],
            ),
          )
          as _i3.Future<List<_i10.CompanyReviewFlag>>);

  @override
  _i3.Future<void> updateCarReview(_i11.UpdateReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateCarReview, [param]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCompanyReview(_i11.UpdateReview? param) =>
      (super.noSuchMethod(
            Invocation.method(#updateCompanyReview, [param]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCarReview(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCarReview, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCompanyReview(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCompanyReview, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
