// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/company/data/repo/company_repo.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kcars/features/car/data/model/city.dart' as _i8;
import 'package:kcars/features/company/data/model/company.dart' as _i2;
import 'package:kcars/features/company/data/model/company_cursor.dart' as _i7;
import 'package:kcars/features/company/data/model/company_statistic.dart'
    as _i9;
import 'package:kcars/features/company/data/model/contact.dart' as _i6;
import 'package:kcars/features/company/data/model/post_company.dart' as _i5;
import 'package:kcars/features/company/data/remote/company_remote.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCompany_0 extends _i1.SmartFake implements _i2.Company {
  _FakeCompany_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CompanyRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyRemote extends _i1.Mock implements _i3.CompanyRemote {
  MockCompanyRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateCompany(_i5.PostCompany? params) =>
      (super.noSuchMethod(
            Invocation.method(#updateCompany, [params]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sortContacts(List<_i6.Contact>? param) =>
      (super.noSuchMethod(
            Invocation.method(#sortContacts, [param]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Company>> companies([_i7.CompanyCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#companies, [param]),
            returnValue: _i4.Future<List<_i2.Company>>.value(<_i2.Company>[]),
          )
          as _i4.Future<List<_i2.Company>>);

  @override
  _i4.Future<String?> newCompany(_i2.Company? param) =>
      (super.noSuchMethod(
            Invocation.method(#newCompany, [param]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i2.Company> company(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#company, [id]),
            returnValue: _i4.Future<_i2.Company>.value(
              _FakeCompany_0(this, Invocation.method(#company, [id])),
            ),
          )
          as _i4.Future<_i2.Company>);

  @override
  _i4.Future<_i2.Company> myCompany([String? id]) =>
      (super.noSuchMethod(
            Invocation.method(#myCompany, [id]),
            returnValue: _i4.Future<_i2.Company>.value(
              _FakeCompany_0(this, Invocation.method(#myCompany, [id])),
            ),
          )
          as _i4.Future<_i2.Company>);

  @override
  _i4.Future<List<_i8.City>> cities() =>
      (super.noSuchMethod(
            Invocation.method(#cities, []),
            returnValue: _i4.Future<List<_i8.City>>.value(<_i8.City>[]),
          )
          as _i4.Future<List<_i8.City>>);

  @override
  _i4.Future<List<_i9.CompanyStatistic>> companyStatistic([DateTime? date]) =>
      (super.noSuchMethod(
            Invocation.method(#companyStatistic, [date]),
            returnValue: _i4.Future<List<_i9.CompanyStatistic>>.value(
              <_i9.CompanyStatistic>[],
            ),
          )
          as _i4.Future<List<_i9.CompanyStatistic>>);

  @override
  _i4.Future<List<_i2.Company>> allCompanies([_i7.CompanyCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#allCompanies, [param]),
            returnValue: _i4.Future<List<_i2.Company>>.value(<_i2.Company>[]),
          )
          as _i4.Future<List<_i2.Company>>);
}
