// Mocks generated by Mockito 5.4.6 from annotations
// in kcars/test/features/booking/data/repo/book_repo_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kcars/features/booking/data/model/book.dart' as _i7;
import 'package:kcars/features/booking/data/model/book_cursor.dart' as _i8;
import 'package:kcars/features/booking/data/model/new_booking.dart' as _i5;
import 'package:kcars/features/booking/data/model/promo_code.dart' as _i6;
import 'package:kcars/features/booking/data/model/promotion_result.dart' as _i2;
import 'package:kcars/features/booking/data/remote/book_remote.dart' as _i3;
import 'package:kcars/features/company/data/model/contact_statistic.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePromotionResult_0 extends _i1.SmartFake
    implements _i2.PromotionResult {
  _FakePromotionResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRemote extends _i1.Mock implements _i3.BookRemote {
  MockBookRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> bookCar([_i5.NewBooking? param]) =>
      (super.noSuchMethod(
            Invocation.method(#bookCar, [param]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i2.PromotionResult> applyPromoCode(_i6.PromoCode? param) =>
      (super.noSuchMethod(
            Invocation.method(#applyPromoCode, [param]),
            returnValue: _i4.Future<_i2.PromotionResult>.value(
              _FakePromotionResult_0(
                this,
                Invocation.method(#applyPromoCode, [param]),
              ),
            ),
          )
          as _i4.Future<_i2.PromotionResult>);

  @override
  _i4.Future<void> cancelUserBooks([_i5.NewBooking? param]) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUserBooks, [param]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Book>> getBooks([_i8.BookCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#getBooks, [param]),
            returnValue: _i4.Future<List<_i7.Book>>.value(<_i7.Book>[]),
          )
          as _i4.Future<List<_i7.Book>>);

  @override
  _i4.Future<List<_i7.Book>> allBooks([_i8.BookCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#allBooks, [param]),
            returnValue: _i4.Future<List<_i7.Book>>.value(<_i7.Book>[]),
          )
          as _i4.Future<List<_i7.Book>>);

  @override
  _i4.Future<List<_i7.Book>> getCompanyBooks([_i8.BookCursor? param]) =>
      (super.noSuchMethod(
            Invocation.method(#getCompanyBooks, [param]),
            returnValue: _i4.Future<List<_i7.Book>>.value(<_i7.Book>[]),
          )
          as _i4.Future<List<_i7.Book>>);

  @override
  _i4.Future<void> updateBook([_i5.NewBooking? param]) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [param]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> contact(_i9.ContactStatistic? param) =>
      (super.noSuchMethod(
            Invocation.method(#contact, [param]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
